### ISSUE TITLE
I can’t Dectect lame on yellowshoes

### ISSUE THREAD

**Issue by elmogosogo09usa** [evuraan/yellowShoes#12] opened 2023-10-18 21:53 UTC
I tried everything on windows to get lame to work however I didn’t have a solution to the problem I have  iOS devices and my server that runs use windows

**Comment by evuraan** [comment] 2023-10-27 19:11
Try placing `lame.exe` into your `%PATH%` before launching `yellowShoes`. 

Or

```powershell
$env:Path += ";C:\FolderWhereLameLives"
```


Closing, not a bug of my creation.

**Closed as completed by evuraan** 2023-10-27 19:10 UTC

**Comment by anmathew** [comment] 2023-12-05 06:46
hi @elmogosogo09usa , can you please try with[ this test build ](https://github.com/evuraan/yellowShoes/issues/14#issuecomment-1840104977)and see if that works?

**Comment by elmogosogo09usa** [comment] 2023-12-28 16:26
Also I should add different audio formats
